"""Gradio UI for the RAG Q&A System.

Runs the QA service in-process (no separate Flask server needed) and exposes a
simple web interface to ask questions, pick a retrieval mode, and inspect the
answer alongside its source citations.

Run:
    python -m rag_qa.ui        # or: rag-ui
    #  http://127.0.0.1:7860
"""

import os

# Load the (already-cached) embedding model straight from disk instead of
# pinging HuggingFace at startup — otherwise a flaky network makes model load
# hang ~90s on HEAD-request timeouts. Running the UI presupposes the corpus
# (and thus the model) is built, so the cache is present. Override by exporting
# HF_HUB_OFFLINE=0 before launch if you want online update checks.
os.environ.setdefault("HF_HUB_OFFLINE", "1")
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")

import gradio as gr

from rag_qa.api import QAService

MODES = ["hybrid", "baseline", "rrf", "cross_encoder"]

EXAMPLE_QUESTIONS = [
    "What are the requirements for emergency stop systems in industrial machinery?",
    "How do you perform a risk assessment according to EN ISO 12100?",
    "What machine guarding methods protect the point of operation?",
    "Explain the difference between SIL and PL safety ratings.",
    "How should lockout/tagout procedures be implemented for maintenance?",
]

# Lazily-initialized singleton so the model/index load once, not per request.
_service = None
_init_error = None


def _default_db_path() -> str:
    return os.environ.get(
        "RAG_DB_PATH",
        os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "rag_database.db"),
    )


def get_service():
    """Return the QAService, or None (with _init_error set) if data is missing."""
    global _service, _init_error
    if _service is None and _init_error is None:
        try:
            _service = QAService(db_path=_default_db_path())
        except Exception as e:  # index/DB not built yet, etc.
            _init_error = str(e)
    return _service


def _render_contexts(contexts) -> str:
    if not contexts:
        return "_No source passages retrieved._"
    lines = ["### Sources"]
    for i, c in enumerate(contexts, 1):
        source = c.get("source") or c.get("file") or "unknown"
        page = c.get("page")
        page_str = f", p.{page}" if page else ""
        url = c.get("url") or ""
        header = f"**{i}. {source}**{page_str}"
        if url:
            header += f"  ·  [link]({url})"
        scores = (f"score {c.get('score', 0):.3f}  |  "
                  f"vector {c.get('vector_score', 0):.3f}  |  "
                  f"bm25 {c.get('bm25_score', 0):.3f}")
        text = (c.get("text") or "").strip()
        if len(text) > 600:
            text = text[:600].rstrip() + "…"
        lines.append(f"{header}\n\n_{scores}_\n\n> {text}\n")
    return "\n".join(lines)


def answer_query(question: str, mode: str, k: int):
    """Gradio callback: returns (answer_md, meta_md, sources_md)."""
    if not question or not question.strip():
        return "Please enter a question.", "", ""

    service = get_service()
    if service is None:
        msg = (
            "### ⚠️ Search index not built yet\n"
            f"Could not initialize the QA service: `{_init_error}`\n\n"
            "Build the corpus first, then reload this page:\n"
            "```bash\n"
            "python scripts/download_pdfs.py\n"
            "bash scripts/rebuild_data.sh\n"
            "```"
        )
        return msg, "", ""

    try:
        resp = service.ask(question.strip(), k=int(k), mode=mode)
    except Exception as e:
        return f"### Error\n`{e}`", "", ""

    confidence = resp.get("confidence", 0.0)
    if resp.get("answer"):
        answer_md = f"### Answer\n{resp['answer']}"
    else:
        answer_md = (f"### No answer — the system abstained\n"
                     f"_{resp.get('abstain_reason', 'Low confidence')}_")

    meta_md = (f"**Confidence:** {confidence:.3f}  ·  "
               f"**Mode:** {resp.get('reranker_used', mode)}  ·  "
               f"**Passages:** {resp.get('total_results', 0)}")

    return answer_md, meta_md, _render_contexts(resp.get("contexts", []))


def build_demo() -> "gr.Blocks":
    with gr.Blocks(title="RAG Q&A — Industrial Safety") as demo:
        gr.Markdown(
            "# 🔍 RAG Q&A — Industrial Safety Documents\n"
            "Ask a question about machine & industrial safety. Answers are "
            "**extractive** (sentences pulled from the source PDFs, ranked by "
            "relevance) with citations — no text is generated by an LLM."
        )
        with gr.Row():
            with gr.Column(scale=3):
                question = gr.Textbox(
                    label="Question", lines=2,
                    placeholder="e.g. What are the requirements for emergency stop systems?",
                )
            with gr.Column(scale=1):
                mode = gr.Radio(MODES, value="hybrid", label="Retrieval mode")
                k = gr.Slider(1, 20, value=5, step=1, label="Passages (k)")
        ask_btn = gr.Button("Ask", variant="primary")

        answer_out = gr.Markdown(label="Answer")
        meta_out = gr.Markdown()
        sources_out = gr.Markdown(label="Sources")

        gr.Examples(examples=[[q] for q in EXAMPLE_QUESTIONS], inputs=[question])

        ask_btn.click(answer_query, [question, mode, k],
                      [answer_out, meta_out, sources_out])
        question.submit(answer_query, [question, mode, k],
                        [answer_out, meta_out, sources_out])
    return demo


def main():
    host = os.environ.get("GRADIO_HOST", "127.0.0.1")
    port = int(os.environ.get("GRADIO_PORT", "7860"))
    build_demo().launch(server_name=host, server_port=port)


if __name__ == "__main__":
    main()
